plan: java-pert c-pert
  pdflatex -interaction batchmode -file-line-error -o ProjectPlan.pdf plan.tex

java-pert:
  dot -Tpdf -o java-pert.pdf Java-PERT.dot

c-pert:
	#dot -Tpdf -o c-pert.pdf C-PERT.dot

